### ISSUE TITLE
"Have all upgrades" flag breaks water in Trial mode

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sadx-super-sonic#16]
If the "Have all upgrades" flag is enabled in the Mod Loader and the game is started in Trial mode with the SuperSonic mod on, you can walk on water in Station Square (sewers area) and Emerald Coast 2 even when you aren't Super Sonic.

The glitch doesn't affect any other characters, only Sonic.

**Comment by SonicFreak94** [comment]
Almost certainly because the code checks for the [Super Sonic upgrade bit](https://github.com/sonicretro/sadx-super-sonic/blob/master/sadx-super-sonic/mod.cpp#L92-L95).

**Comment by SonicFreak94** [comment]
This is no longer an issue.
