### ISSUE TITLE
Music Bug in Speed Highway 2

### ISSUE THREAD

**Issue by cheatfreak47** [sonicretro/sadx-super-sonic#2]
Using ADX sound, "Goin Down!" Starts playing before immediately switching to Super Sonic, didn't happen in Endri's Mod.

**Comment by michael-fadely** [comment]
Looks like this is due to the result screen hack which will avoid changing music if P1's control is disabled.

**Comment by michael-fadely** [comment]
Fixed in two ways now: Music is set less aggressively, and Super Sonic is disabled in Goin' Down. Not sure about keeping the latter, but Super Sonic is pretty uncontrollable there.
