### ISSUE TITLE
Support Dreamcast Characters Pack Super Sonic Model

### ISSUE THREAD

**Issue by Danfun64** [sonicretro/sadx-super-sonic#20]
A feature request. It would be really nice if this had the ability to take advantage of the Dreamcast Super Sonic model, especially as the "SADX Mods Installer" has this mod as an option.

**Comment by cheatfreak47** [comment]
Uh, I'm pretty sure it already does?

**Comment by michael-fadely** [comment]
yeah this works fine already with the dreamcast character models

**Comment by Danfun64** [comment]
"Super Sonic - x-hax - 1.2"? Because while that worked with the dreamcast models mod on per se, it loaded the SADX Super Sonic model when 50 rings are collected.

Also the Super Sonic mod has no configuration settings whatsoever in the Mod Manager.

**Comment by michael-fadely** [comment]
![h7ikckd](https://user-images.githubusercontent.com/920569/40030448-dbcd3d1c-57a7-11e8-93d6-dbe6ca6988bd.png)

**Comment by ItsEasyActually** [comment]
That shouldn't be possible at all. Super Sonic's entire model is rewritten in the SA1_Chars mod, and there are no references back to the original. 

And why would this mod need config options...?

**Comment by Danfun64** [comment]
To turn on and off the (hypothetical apparently) rewritten Dreamcast Super Sonic model.

**Comment by ItsEasyActually** [comment]
It's not hypothetical, it literally can't happen. The coding doesn't allow for it as, like I said, his entire model is rewritten and nothing in the exe or this mod references the data in a way to force load Super Sonic at all.

**Comment by Danfun64** [comment]
I meant rewritten for this mod.
